// SPDX-FileCopyrightText: 2026 Philippe Vollenweider
// SPDX-License-Identifier: AGPL-3.0-only

import fs from "node:fs"
import path from "node:path"
import type { Metadata } from "next"
import { z } from "zod"
import { SITE_NAME, splitTitle } from "@/lib/doc-pages"
import { findVideoReferences } from "@/lib/doc-video-references"

/**
 * The documentation split into units (#649): one Markdown file per task in the root folder
 * `guide/` (`guide/<slug>.md`), rendered at `/doc/<slug>` (src/app/doc/[slug]/page.tsx). Each
 * file opens with a small flat front matter, then its own « # » title (the page's single <h1>):
 *
 *     ---
 *     roles: [benevole]
 *     group: apres-inscription
 *     order: 10
 *     summary: One sentence of 60 to 160 characters, also the page's meta description.
 *     related: [another-unit]
 *     legacy: [benevole#old-anchor]
 *     aliases: [old-slug]
 *     ---
 *
 *     # Title of the unit
 *
 * The file is the only copy of the content, readable on GitHub as well; `guide/README.md` is its
 * index, generated by `npm run doc:index` (scripts/doc-index.ts). The parser and the checks are
 * pure; only `loadDocUnits` touches the disk (server side, like src/lib/public-content.ts).
 */

/** The two audiences of the documentation: organisers (`/doc/admin`) and volunteers (`/doc/benevole`). */
export const DOC_ROLES = ["admin", "benevole"] as const
export type DocRole = (typeof DOC_ROLES)[number]

/**
 * Each role's name in « Pour : … », and its guide: the link is named after its target
 * (« Guide bénévole »), the audience stays plain text.
 */
export const DOC_ROLE_INFO: Record<DocRole, { label: string; path: string; guideTitle: string }> = {
  admin: { label: "organisateurs", path: "/doc/admin", guideTitle: "Guide administrateur" },
  benevole: { label: "bénévoles", path: "/doc/benevole", guideTitle: "Guide bénévole" },
}

export type DocGroup = { id: string; title: string }

/**
 * The groups of the documentation, in reading order: a unit names its group in its front matter,
 * the breadcrumb and the index show the group's title. Groups are added here as the guides are
 * split (volunteer units first, organiser units later).
 */
export const DOC_GROUPS: readonly DocGroup[] = [
  { id: "inscription", title: "S'inscrire à un créneau" },
  { id: "apres-inscription", title: "Après l'inscription" },
  { id: "regles", title: "Règles d'inscription" },
  { id: "demarrer", title: "Démarrer" },
  { id: "preparer", title: "Préparer l'événement" },
  { id: "publier", title: "Publier et partager" },
  { id: "suivre", title: "Suivre l'événement" },
  { id: "jour-j", title: "Le jour J" },
  { id: "membres", title: "Membres et invitations" },
  { id: "communiquer", title: "Communiquer avec les bénévoles" },
  { id: "organisation", title: "Paramètres de l'organisation" },
  { id: "aide", title: "Aide" },
]

/**
 * Slugs a unit can never take: the static pages under src/app/doc win over the dynamic segment,
 * so a unit with one of these slugs would never be shown. A test checks that every static folder
 * of src/app/doc is listed here.
 */
export const RESERVED_DOC_SLUGS: readonly string[] = ["admin", "benevole"]

/** The folder of the units, at the repo root. */
export const DOC_UNITS_DIR = "guide"

/** The generated index of `guide/`, not a unit. */
export const DOC_INDEX_FILE = "README.md"

const SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
const LEGACY_RE = /^(admin|benevole)#[a-z0-9]+(?:-[a-z0-9]+)*$/

/** Separators the copy never uses (accessibility: read aloud as noise, or not at all). */
const FORBIDDEN_SEPARATORS = /[·—]/

// ---------------------------------------------------------------------------------------------
// Front matter
// ---------------------------------------------------------------------------------------------

export type FrontMatterValue = string | string[]

/**
 * Parses the flat front matter of a unit: `key: value` or `key: [a, b]`, one per line, between two
 * `---` lines at the very top of the file. No nesting, no quotes, no multi-line value: anything
 * else is an error, so a typo never passes silently. Returns the fields and the rest of the file.
 */
export function parseFrontMatter(source: string): { data: Record<string, FrontMatterValue>; body: string } {
  const text = source.replace(/\r\n/g, "\n")
  if (!text.startsWith("---\n")) throw new Error("front matter missing: the file must start with a --- line")
  const end = text.indexOf("\n---\n", 3)
  if (end === -1) throw new Error("front matter not closed: a --- line is missing")
  const data: Record<string, FrontMatterValue> = {}
  const lines = text.slice(4, end).split("\n")
  lines.forEach((line, index) => {
    if (line.trim() === "") return
    const match = line.match(/^([a-z][a-z0-9_]*):(?: (.*))?$/)
    if (!match) throw new Error(`front matter line ${index + 2}: expected « key: value », got « ${line} »`)
    const [, key, rawValue = ""] = match
    if (key in data) throw new Error(`front matter line ${index + 2}: duplicate key « ${key} »`)
    const value = rawValue.trim()
    if (value.startsWith("[")) {
      if (!value.endsWith("]")) throw new Error(`front matter line ${index + 2}: list not closed`)
      const inner = value.slice(1, -1).trim()
      data[key] = inner === "" ? [] : inner.split(",").map((item) => item.trim())
      if ((data[key] as string[]).some((item) => item === "")) throw new Error(`front matter line ${index + 2}: empty list item`)
    } else {
      data[key] = value
    }
  })
  return { data, body: text.slice(end + "\n---\n".length) }
}

const slugList = z.array(z.string().regex(SLUG_RE, "slug: lower case letters, digits and hyphens")).default([])

/** The front matter's schema: unknown keys are rejected (a misspelt key would be ignored otherwise). */
export const docUnitFrontMatterSchema = z.strictObject({
  roles: z
    .array(z.enum(DOC_ROLES))
    .min(1, "at least one role")
    .refine((roles) => new Set(roles).size === roles.length, "a role is listed twice"),
  group: z.string().refine((id) => DOC_GROUPS.some((g) => g.id === id), "unknown group (see DOC_GROUPS in src/lib/doc-units.ts)"),
  order: z.string().regex(/^\d+$/, "order: a whole number").transform(Number),
  summary: z
    .string()
    .min(60, "summary: at least 60 characters")
    .max(160, "summary: at most 160 characters")
    .refine((s) => !FORBIDDEN_SEPARATORS.test(s), "summary: no « · » or em dash"),
  related: slugList,
  legacy: z.array(z.string().regex(LEGACY_RE, "legacy: role#anchor, e.g. benevole#confirmation")).default([]),
  aliases: slugList,
})

export type DocUnit = {
  slug: string
  /** The file's own « # » title. */
  title: string
  roles: DocRole[]
  group: string
  order: number
  summary: string
  related: string[]
  /** Anchors of the old single-page guides this unit replaces (`benevole#confirmation`), for their redirect. */
  legacy: string[]
  /** Former slugs of this unit, permanently redirected to it. */
  aliases: string[]
  /** The Markdown after the title. */
  body: string
  /** Path of the source from the repo root, e.g. `guide/confirmation.md`. */
  source: string
}

/** One unit from its file name and content; throws with the file name on any error. */
export function parseDocUnit(fileName: string, source: string): DocUnit {
  const slug = fileName.replace(/\.md$/, "")
  const fail = (message: string): never => {
    throw new Error(`${DOC_UNITS_DIR}/${fileName}: ${message}`)
  }
  if (!fileName.endsWith(".md") || !SLUG_RE.test(slug)) fail("file name: lower case letters, digits and hyphens, then .md")
  let parsed: ReturnType<typeof parseFrontMatter>
  try {
    parsed = parseFrontMatter(source)
  } catch (error) {
    return fail((error as Error).message)
  }
  const result = docUnitFrontMatterSchema.safeParse(parsed.data)
  if (!result.success) fail(result.error.issues.map((i) => `${i.path.join(".") || "front matter"}: ${i.message}`).join("; "))
  const { title, body } = splitTitle(parsed.body.replace(/^\n+/, ""))
  if (!title) fail("the first line after the front matter must be the « # » title")
  if (/^# /m.test(body)) fail("one « # » title only (the page's single <h1>)")
  const data = result.data!
  return { slug, title: title!, ...data, body, source: `${DOC_UNITS_DIR}/${fileName}` }
}

/**
 * The problems of a set of units, as messages (empty when all is well): reserved or duplicate
 * slugs, aliases colliding with a slug, unknown related units, titles or summaries used twice,
 * more than one video per unit, forbidden separators in a title or a summary.
 */
export function docUnitProblems(units: readonly DocUnit[], reserved: readonly string[] = RESERVED_DOC_SLUGS): string[] {
  const problems: string[] = []
  const slugs = new Set(units.map((u) => u.slug))
  const seenAliases = new Map<string, string>()
  const seenTitles = new Map<string, string>()
  const seenSummaries = new Map<string, string>()
  for (const unit of units) {
    if (reserved.includes(unit.slug)) problems.push(`${unit.slug}: reserved slug (a static page of /doc)`)
    for (const alias of unit.aliases) {
      if (reserved.includes(alias)) problems.push(`${unit.slug}: alias « ${alias} » is a reserved slug`)
      if (slugs.has(alias)) problems.push(`${unit.slug}: alias « ${alias} » is the slug of a unit`)
      const other = seenAliases.get(alias)
      if (other) problems.push(`${unit.slug}: alias « ${alias} » already used by ${other}`)
      seenAliases.set(alias, unit.slug)
    }
    for (const related of unit.related) {
      if (related === unit.slug) problems.push(`${unit.slug}: related to itself`)
      else if (!slugs.has(related)) problems.push(`${unit.slug}: related unit « ${related} » doesn't exist`)
    }
    const titleOwner = seenTitles.get(unit.title)
    if (titleOwner) problems.push(`${unit.slug}: same title as ${titleOwner}`)
    seenTitles.set(unit.title, unit.slug)
    const summaryOwner = seenSummaries.get(unit.summary)
    if (summaryOwner) problems.push(`${unit.slug}: same summary as ${summaryOwner}`)
    seenSummaries.set(unit.summary, unit.slug)
    if (FORBIDDEN_SEPARATORS.test(unit.title)) problems.push(`${unit.slug}: no « · » or em dash in the title`)
    if (FORBIDDEN_SEPARATORS.test(unit.summary)) problems.push(`${unit.slug}: no « · » or em dash in the summary`)
    if (findVideoReferences(unit.body).length > 1) problems.push(`${unit.slug}: one video at most per unit`)
  }
  const legacyOwners = new Map<string, string>()
  for (const unit of units) {
    for (const anchor of unit.legacy) {
      const other = legacyOwners.get(anchor)
      if (other) problems.push(`${unit.slug}: legacy anchor « ${anchor} » already claimed by ${other}`)
      legacyOwners.set(anchor, unit.slug)
    }
  }
  return problems
}

/** Units in reading order: by group (DOC_GROUPS order), then `order`, then slug. */
export function sortDocUnits(units: readonly DocUnit[]): DocUnit[] {
  const groupIndex = (id: string) => DOC_GROUPS.findIndex((g) => g.id === id)
  return [...units].sort((a, b) => groupIndex(a.group) - groupIndex(b.group) || a.order - b.order || a.slug.localeCompare(b.slug))
}

/** Reads, parses and checks every unit of `guide/` (server only); throws on the first broken file or any problem. */
export function readDocUnits(dir: string = path.join(process.cwd(), DOC_UNITS_DIR)): DocUnit[] {
  if (!fs.existsSync(dir)) return []
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".md") && f !== DOC_INDEX_FILE)
  const units = files.map((f) => parseDocUnit(f, fs.readFileSync(path.join(dir, f), "utf-8")))
  const problems = docUnitProblems(units)
  if (problems.length > 0) throw new Error(`documentation units:\n${problems.join("\n")}`)
  return sortDocUnits(units)
}

// The units don't change while the server runs (they're in the image): production reads them
// once; development reads them again on each request, so editing a unit shows up.
let cachedUnits: DocUnit[] | null = null
export function loadDocUnits(): DocUnit[] {
  if (process.env.NODE_ENV !== "production") return readDocUnits()
  cachedUnits ??= readDocUnits()
  return cachedUnits
}

// ---------------------------------------------------------------------------------------------
// Lookups and presentation
// ---------------------------------------------------------------------------------------------

/** What `/doc/<slug>` shows: the unit, a permanent redirect to the unit's current slug, or nothing. */
export function resolveDocSlug(slug: string, units: readonly DocUnit[]): { unit: DocUnit } | { redirectTo: string } | null {
  const unit = units.find((u) => u.slug === slug)
  if (unit) return { unit }
  const renamed = units.find((u) => u.aliases.includes(slug))
  return renamed ? { redirectTo: `/doc/${renamed.slug}` } : null
}

/**
 * Where an anchor of the old single-page guides now lives (`/doc/benevole#confirmation` →
 * `/doc/confirmation`), from the units' `legacy` lists; null when no unit claims it. When the unit
 * has a heading with the same id (a subsection moved as is; `headingIds` gives a unit's heading
 * ids), the fragment is kept: `/doc/confirmation#modifier`.
 */
export function resolveLegacyAnchor(
  role: DocRole,
  anchor: string,
  units: readonly DocUnit[],
  headingIds: (unit: DocUnit) => readonly string[] = () => [],
): string | null {
  const key = `${role}#${anchor}`
  const unit = units.find((u) => u.legacy.includes(key))
  if (!unit) return null
  return headingIds(unit).includes(anchor) ? `/doc/${unit.slug}#${anchor}` : `/doc/${unit.slug}`
}

/**
 * Every old anchor of a role's guide that a unit claims, with its target (resolveLegacyAnchor):
 * the map the guide's page hands to its client-side redirect (src/app/doc/LegacyAnchorRedirect.tsx).
 */
export function legacyAnchorTargets(
  role: DocRole,
  units: readonly DocUnit[],
  headingIds: (unit: DocUnit) => readonly string[] = () => [],
): Record<string, string> {
  const targets: Record<string, string> = {}
  const prefix = `${role}#`
  for (const unit of units) {
    for (const key of unit.legacy) {
      if (!key.startsWith(prefix)) continue
      const anchor = key.slice(prefix.length)
      targets[anchor] = resolveLegacyAnchor(role, anchor, units, headingIds)!
    }
  }
  return targets
}

/**
 * The units of a role (every unit without one), by group in DOC_GROUPS order and in reading order
 * within a group; a group without any unit is left out. What the indexes of /doc show.
 */
export function docUnitsByGroup(units: readonly DocUnit[], role?: DocRole): { group: DocGroup; units: DocUnit[] }[] {
  const sorted = sortDocUnits(role ? units.filter((u) => u.roles.includes(role)) : units)
  return DOC_GROUPS.map((group) => ({ group, units: sorted.filter((u) => u.group === group.id) })).filter((g) => g.units.length > 0)
}

/** Whether a role's guide has units yet: its page then lists them above « Le guide complet ». */
export function roleHasDocUnits(units: readonly DocUnit[], role: DocRole): boolean {
  return units.some((u) => u.roles.includes(role))
}

/** « organisateurs, bénévoles »: who a unit is for, as the indexes write it. */
export function docUnitAudience(unit: DocUnit): string {
  return unit.roles.map((r) => DOC_ROLE_INFO[r].label).join(", ")
}

/** Where a group is listed on the documentation's index: the breadcrumb of a unit links there. */
export function docGroupHref(group: DocGroup): string {
  return `/doc#${group.id}`
}

export function docGroup(id: string): DocGroup {
  const group = DOC_GROUPS.find((g) => g.id === id)
  if (!group) throw new Error(`Unknown documentation group: ${id}`)
  return group
}

/** The units a unit links to under « Voir aussi », in the order its front matter lists them. */
export function relatedDocUnits(unit: DocUnit, units: readonly DocUnit[]): DocUnit[] {
  return unit.related.flatMap((slug) => units.filter((u) => u.slug === slug))
}

/** Metadata of a unit's page: its title and summary, an absolute canonical on the apex host, Open Graph, indexable. */
export function docUnitMetadata(unit: DocUnit, base: string): Metadata {
  const url = `${base.replace(/\/+$/, "")}/doc/${unit.slug}`
  const title = `${unit.title} — ${SITE_NAME}`
  return {
    title,
    description: unit.summary,
    alternates: { canonical: url },
    openGraph: { type: "article", siteName: SITE_NAME, locale: "fr_CH", url, title, description: unit.summary },
    robots: { index: true, follow: true },
  }
}

// ---------------------------------------------------------------------------------------------
// guide/README.md
// ---------------------------------------------------------------------------------------------

export const DOC_INDEX_START = "<!-- doc-index:start (generated by npm run doc:index, do not edit) -->"
export const DOC_INDEX_END = "<!-- doc-index:end -->"

/** The list of `guide/README.md`: every unit by group, linked by file so it works on GitHub. */
export function docIndexMarkdown(units: readonly DocUnit[]): string {
  const sorted = sortDocUnits(units)
  const sections = DOC_GROUPS.flatMap((group) => {
    const inGroup = sorted.filter((u) => u.group === group.id)
    if (inGroup.length === 0) return []
    const items = inGroup.map((u) => `- [${u.title}](${u.slug}.md) : ${u.summary} Pour : ${docUnitAudience(u)}.`)
    return [`### ${group.title}\n\n${items.join("\n")}`]
  })
  return sections.length > 0 ? sections.join("\n\n") : "Aucune page pour l'instant."
}

/** `markdown` with its generated index replaced by `index`. */
export function withDocIndex(markdown: string, index: string): string {
  const i = markdown.indexOf(DOC_INDEX_START)
  const j = markdown.indexOf(DOC_INDEX_END)
  if (i === -1 || j === -1 || j < i) throw new Error("doc index markers missing")
  return `${markdown.slice(0, i + DOC_INDEX_START.length)}\n${index}\n${markdown.slice(j)}`
}
