apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: benevol-app-wildcard
  namespace: benevoles
spec:
  secretName: benevol-app-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.benevol.app"
    - "benevol.app"
    - "www.benevol.app"
