apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: benevoles-app
  namespace: benevoles
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.priority: "100"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - benevol.app
      secretName: benevol-app-tls
  rules:
    - host: benevol.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: benevoles-app
                port:
                  number: 80
