apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: benevoles-app
  namespace: benevoles
spec:
  ingressClassName: traefik
  rules:
    - host: benevoles.gallerypack.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: benevoles-app
                port:
                  number: 80
